### ISSUE TITLE
Text selection (macOS Monterey)

### ISSUE THREAD

**Issue by kuglee** [sbarex/SourceCodeSyntaxHighlight#110]
Thanks for this great app.

I know macOS Monterey not officially supported yet, but macOS Monterey restored the ability to copy text from the Quick Look window. It would be nice to have text selection working with this plugin.

**Comment by sbarex** [comment]
Oh, I didn't know about this new feature. Do you know if it has been included in any documentation? 

When Monterey is released and I can install it I will try to understand if it is implementable in my app.

**Comment by kuglee** [comment]
Unfortunately I don't know of any documentation regarding this.

**Comment by hazarek** [comment]
> Unfortunately I don't know of any documentation regarding this.

Can't I drag from the middle of the Quicklook window on macOS Monterey? Can you post a sample demo video here?

**Comment by Altair-Bueno** [comment]
I've noticed QLMarkdown allows copying out-of-the-box on Monterey. It may be something missing on Syntax Highlighting that QLMarkdown has

> Note: [QLMarkdown](https://github.com/sbarex/QLMarkdown) is another QL Plugin made by sbarex

**Comment by sbarex** [comment]
Yes, I am working to adopt the new Monterey api in this application as well.

**Comment by sbarex** [comment]
This features in now available on release 2.1.0.

**Comment by vpicouet** [comment]
This is great, Thanks a lot!!!
Just for those who struggle of copying text because of the line number, I remind here that if you hit option you can do some rectangle selection and multiple selection with command key ... 
That makes it such a good app!
Thanks!!

![Capture d’écran, le 2022-04-15 à 11 45 08](https://user-images.githubusercontent.com/37241971/163591551-75e6c574-dc46-4516-a1c2-594264e36292.jpg)

![Capture d’écran, le 2022-04-15 à 11 46 08](https://user-images.githubusercontent.com/37241971/163591648-0f00cde7-7bb9-4802-941e-4a995753693c.jpg)

**Comment by sbarex** [comment]
Rectangular selection and multi selection are available only when you use the `RTF` engine. In the `HTML` engine, despite having disabled the selection of line numbers, they are kept in the copy.
