### ISSUE TITLE
Not responding on 890KB js file.

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#111]
try this file -> https://github.com/justinwilaby/svg-path-interpolator/blob/master/examples/animatePaths/animation.js

Data Limit 1MB -  endless loading

https://user-images.githubusercontent.com/36481442/136085358-ab5dd2d9-05c5-4524-ac24-c43e223c3927.mp4

Data Limit 300KB - 30 second / output truncated

https://user-images.githubusercontent.com/36481442/136085598-a7807bc0-4d4c-4de4-9972-0aa7e4fc358b.mp4

**Comment by sbarex** [comment]
On my system it is not particularly slow. What settings are you using? 
Can you activate the debug mode and post the content of the created colorize.log file created on the desktop?

**Comment by hazarek** [comment]
[colorize.log](https://github.com/sbarex/SourceCodeSyntaxHighlight/files/7288947/colorize.log)

**Comment by hazarek** [comment]
[colorize1MB.log](https://github.com/sbarex/SourceCodeSyntaxHighlight/files/7288959/colorize1MB.log)
Data Limit = 1MB endless

**Comment by hazarek** [comment]
I solved the problem as follows.;

Render Engine: RTF
Word wrap: Hard Wrap
Data limit: 50KB

**Comment by sbarex** [comment]
Looking in your log file I see that in your system the generation of the formatted code takes about 1 second.
The generated html file has a weight of almost 10mb (if you enable the debug settings a `colorize.html` will be created on your desktop with the result of the rendering). 

The slowness of viewing is due to the time required by WebKit to process and view the file. On macOS 12 Monterey the new api is more fast, but in any case the delay is perceived. 

If you try to show with the sistem Quick Look the `colorize.html` file you will see that there will be a delay similar to that present in my application.
