### ISSUE TITLE
The operation couldn’t be completed

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#123]
The operation couldn’t be completed. ((extension in Syntax_Highlight_XPC_Render):Swift.String.TokenizeError error 0.)

**Comment by sbarex** [comment]
does the problem keep showing up?

**Comment by hazarek** [comment]
I reinstalled (v2.1.3) and fixed. Thanks.

**Comment by semvis123** [comment]
![image](https://user-images.githubusercontent.com/28219076/156597976-bb1db301-5aeb-4a33-9583-59e607753dd7.png)

Had the same issue, turned out there was a space in the `Extra Highlight Arguments` field, removing that fixed the issue.
Maybe it could trim the value before saving or using it to avoid the error.

**Comment by sbarex** [comment]
Fixed on release 2.1.9
