### ISSUE TITLE
Support .rst (restructured text) files

### ISSUE THREAD

**Issue by anjos** [sbarex/SourceCodeSyntaxHighlight#159]
Thanks for this awesome plugin.  Very useful.

Would it be possible to add support for this type of markup files?  Reference is here: https://docutils.sourceforge.io/rst.html

I can help if needed.  Thanks in advance!

**Comment by sbarex** [comment]
It seems to me that it is not a format supported by the [Highlight](http://www.andre-simon.de/doku/highlight/en/langs.php) rendering engine. 

It may be possible to handle it if it is a language that follows a syntax quite the same as other languages.

Also it is not clear to me if the purpose would be to display the formatted source code, or to show the rendered output. The latter eventuality would be against the philosophy of the project (which is why even the markdown files are not managed but left to other plugins for their formatting).

**Comment by anjos** [comment]
I agree that rendering would follow out of scope.  I meant just peeking with minimal syntax highlighting.

RST is supported by that engine, following the link you provided.  So is markdown - not sure what you meant by "not managed but left to other plugins for their formatting" - being a newbie here...

**Comment by sbarex** [comment]
True, I hadn't seen it supported. Then I'll add it in the next release.

Regarding markdown I do not manage it with this application because users want to see the formatted output and not the source code. For this I have created another program: [QLMarkdown](https://github.com/sbarex/qlmarkdown).

**Comment by sbarex** [comment]
It is not possible for the user to enable / disable single file support for a Quick Look extension. 

QLMarkdown has a setting to enable the display of highlighted source code instead of formatted output.

**Comment by sbarex** [comment]
Implemented on release 2.1.11.

**Comment by anjos** [comment]
Noted, thanks!
