### ISSUE TITLE
Many file extensions have ASCII problems

### ISSUE THREAD

**Issue by cycle2zhou** [sbarex/SourceCodeSyntaxHighlight#192]
Json and.properties have ASCII problems

Json can be added by adding a preprocessor to solve the beautification problem, but native Python3 to solve the ASCII problem parameters do not support, so can not solve the ASCII problem; Command: python3 -m json.tool --no-ensure-ascii $targetHL

Use version  2.1.15

_Originally posted by @cycle2zhou in https://github.com/sbarex/SourceCodeSyntaxHighlight/issues/156#issuecomment-1245410858_

**Comment by sbarex** [comment]
I removed the default preprocessor for the json format some time ago because it failed to process non-perfectly compliant files. But if you changed the settings it may have remained set after the updates.

In your example the preprocessor is misconfigured:
``` python -m json.tool: error: unrecognized arguments: --no-ensure-ascii ```

This is the output without a preprocessor:
<img width="377" alt="Schermata 2022-09-14 alle 08 14 19" src="https://user-images.githubusercontent.com/1948940/190075555-d63735c4-a55a-4d31-a584-1c5b9b98c621.png">

**Comment by cycle2zhou** [comment]
Sorry about the wrong file, this is the file in question

[file.zip](https://github.com/sbarex/SourceCodeSyntaxHighlight/files/9565029/file.zip)

**Comment by cycle2zhou** [comment]
> I removed the default preprocessor for the json format some time ago because it failed to process non-perfectly compliant files. But if you changed the settings it may have remained set after the updates.
> 
> In your example the preprocessor is misconfigured: `python -m json.tool: error: unrecognized arguments: --no-ensure-ascii`
> 
> This is the output without a preprocessor: <img alt="Schermata 2022-09-14 alle 08 14 19" width="377" src="https://user-images.githubusercontent.com/1948940/190075555-d63735c4-a55a-4d31-a584-1c5b9b98c621.png">

This picture involves the name of the company and the name of the personnel, please type the code or delete it, thank you
