### ISSUE TITLE
Support for .R

### ISSUE THREAD

**Issue by d4tum** [sbarex/SourceCodeSyntaxHighlight#20]
Please add support for .R files from the R programming language. I tried running the command but macOS mis-identifies it as a .rez file:
`mdls -name kMDItemContentType -name kMDItemContentTypeTree 2.1_vectors.R`
shows:
```kMDItemContentType     = "com.apple.rez-source"
kMDItemContentTypeTree = (
    "com.apple.rez-source",
    "public.source-code",
    "public.plain-text",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)

**Comment by sbarex** [comment]
Unfortunately Apple has registered the extension .r for its format. However, although the finder indicates "Rez Source" as type, the program in the next release (b14) will supports syntax highlighting for .r files.
I don't have an apple rez file to see what happens when it tries to be viewed with the application.
