### ISSUE TITLE
Very CPU consuming...

### ISSUE THREAD

**Issue by vpicouet** [sbarex/SourceCodeSyntaxHighlight#21]
Hello,
my mac ran slow and I realized that was syntax highlight that was eating 500% CPU.
I was not even using it... I had to shut it down with Activity monitor (quitting the app did not help).

Vincent

![Capture d’écran, le 2019-11-25 à 12 18 28](https://user-images.githubusercontent.com/37241971/69536287-fee57280-0f7d-11ea-9634-9a0972c05dba.jpg)

**Comment by sbarex** [comment]
The cpu is busy always or only when preview a file?

**Comment by vpicouet** [comment]
I was not previewing any file but it is not always neither.
For instance it is now back to normal (even when previewing a large file), I can let you know when it happens again.

**Comment by sbarex** [comment]
MacOS automatically releases the resources after a few seconds when the preview has been closed.

**Comment by vpicouet** [comment]
Well appears to often consume a lot of CPU... Even when i do not use any preview.
![image](https://user-images.githubusercontent.com/37241971/69546882-da48c500-0f94-11ea-8ae2-1771c4bd044e.jpeg)

**Comment by vpicouet** [comment]
![image](https://user-images.githubusercontent.com/37241971/69547193-68bd4680-0f95-11ea-890d-375069149944.jpeg)

**Comment by sbarex** [comment]
If the process is still running even after the quicklook closes, it probably has crashed.
did you change anything in the program settings?

The about process is the webkit preview. The strange thing is that the preview is not interactive but a simple static html page. So therefore it should not engage the processor.

I would try to disable the extension of the system preferences / extensions / quicklook. Then force all processes to close. Delete the application. Reinstall it and re-enable the plugin in system preferences.

As a further modification you could enable the rtf format instead of html in the application preferences and see if it improves.

**Comment by shen9712** [comment]
I encountered the same problem that ':about' was using 99% CPU until I killed it.
I have never changed any settings ever.
15.5
MacBook 13" 2018

**Comment by sbarex** [comment]
Without knowing what type of file (and its contents) was processing it is difficult to replicate the problem.
Since the offending process is owned by webkit, try set RTF as the output mode in the settings window.
