### ISSUE TITLE
support for more file types

### ISSUE THREAD

**Issue by zhyiyu** [sbarex/SourceCodeSyntaxHighlight#47]
I have turned on the support for `makefile` and `.tex` files

<img width="1241" alt="makefile" src="https://user-images.githubusercontent.com/26550166/99193786-38902a00-2749-11eb-9d1c-68c661befd2d.png">
<img width="1241" alt="latex" src="https://user-images.githubusercontent.com/26550166/99193791-3e860b00-2749-11eb-8d98-7a0d29b04e03.png">

but texts in those files are either not shown or not highlighted

<img width="700" alt="makefile" src="https://user-images.githubusercontent.com/26550166/99193829-886ef100-2749-11eb-9293-c4a91d90cbcb.png">
<img width="924" alt="latex" src="https://user-images.githubusercontent.com/26550166/99193841-902e9580-2749-11eb-8bc4-2c182112708a.png">

other files like Python scripts works fine, am I doing something wrong?

---

Also, are we going to support pure text files that have no suffix, like bash executable scripts and so on? It would be super nice to be able to view them with highlights!

Thanks!

**Comment by sbarex** [comment]
Makefile support is only for `.mk` and `.mak` file (so not for the main Makefile wihout extension).

Also, you cannot "turn on" support for some file format. All formats are handled by default (Apple don't allow to enable/disable support of file handled by a ql extension). In the settings of each format you can customize the appearance overriding the option set in the global settings.

The `tex` file UTI is defined (with different id) by many applications, so is possibile that my extension do not recognize the format (Apple use the UTI for the recognization and not the extension). Also is possibile that the UTI is handled by another ql extension.
Please open the `Inquiry window` (menu `View`/`Inquiry file format`) and drag your tex file inside it. What is the result?

Then, in the `Global settings` enable the `debug flag`, and try to open the ql preview of a tex file. Two files will be created in your desktop (`colorize.log` and `colorize.html` or `.rtf`). Can you post the contents of colorize.log?

Finally for the support of files without extension I am evaluating the opportunity to enable it. The problem is that the utility being used for formatting (`highligth`) require the file extension to operate. It would therefore be necessary to recognize in another way (from the file name, from the content, etc.) the type of file to process it, complicating the application logic. 

For files without extension I use the [qlstephen](https://github.com/whomwah/qlstephen) qlgenerator, which although old and does not format the content, still does its job well.

**Comment by zhyiyu** [comment]
Thank you for your detailed replies! I appreciate!

I totally understand that the inclusion of files with no suffix can be complicated, thank you for explaining that.

As for the inquiry for `.tex` files, here it is

<img width="711" alt="tex inquiry" src="https://user-images.githubusercontent.com/26550166/99470042-0b42a800-2912-11eb-95cf-cfc16909289f.png">

And I tried to produce `colorize.log` for the `.tex` files, but it never get produced. I tried to do the same for `.py` files (which works fine) and the `colorize.log` file is produced right away. So I think this is because that the `.tex` files are not handled. But I have no clue of how to have `.tex` handled.

Thank you so much!

**Comment by sbarex** [comment]
Yes, the `colorize.log` is created only when the extension handle a recognized file.
I see that on you system `.tex` files are set to `edu.uo.texshop` UTI that I do not handled in my app.
In next release I add this new UTI to the list of handled files.

**Comment by zhyiyu** [comment]
Here it is

<img width="1036" alt="tex inquiry" src="https://user-images.githubusercontent.com/26550166/99567986-d9c2ee80-299c-11eb-83f4-c04b7f0c2df6.png">

Thank you!

**Comment by sbarex** [comment]
Last release [1.0.b28](https://github.com/sbarex/SourceCodeSyntaxHighlight/releases/tag/1.0.b28) have the support for edu.uo.textshop.tex uti.

**Comment by zhyiyu** [comment]
Is there a `upgrade` button within the app?

**Comment by sbarex** [comment]
No, you must download the new release and replace the app.

**Comment by sbarex** [comment]
I try to use the sparkle framework for handle the application auto upgrade. For now sparkle do not handle sandboxed app (the support is in the version 2, now in beta).
So I will provide this functionality in the future.
