### ISSUE TITLE
.svelte & .pcss

### ISSUE THREAD

**Issue by belafonte** [sbarex/SourceCodeSyntaxHighlight#55]
Seems highlight supports .svelte and .pcss (postcss) files, at least the inquiry dialog tells me that.

.svelte

kMDItemContentType     = "dyn.ah62d4rv4ge81g7xfrv4gn"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge81g7xfrv4gn",
    "public.data"
)

.pcss

kMDItemContentType     = "dyn.ah62d4rv4ge81a25xsq"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge81a25xsq",
    "public.data"
)

Would be cool for web development.
But anyway this tool is such a gem, thank you!

**Comment by sbarex** [comment]
Hi,
I did not know these formats. 

However, I discovered that there is a bug in recognizing highlight supported files. In practice, therefore, the .svelte and .pcss formats are not supported. I don't know if the formats are a derivation of others (eg html or css) and if for them the highlight of the original format is acceptable rather than nothing.
