### ISSUE TITLE
Word-Wrap as an option in the preview

### ISSUE THREAD

**Issue by NylonDiamond** [sbarex/SourceCodeSyntaxHighlight#6]
Hey, thanks for all the work so far. It would be cool if we could toggle word-wrap on and off in order to avoid scrolling sideways to view all the code in the quick previews. There may be a way to do it but I'm unaware of it. I attached an image of the issue I'm having. Thanks.
![image](https://user-images.githubusercontent.com/19392284/67534039-272d3900-f681-11e9-9f31-1628c393b65d.png)

**Comment by sbarex** [comment]
It was a function that I thought I could add already in the day. In the meantime you can enter the -W parameter in the extra arguments field on app preferences.

**Comment by NylonDiamond** [comment]
Awesome, thanks! Where is the documentation for the arguments?

**Comment by alexclst** [comment]
In Terminal just type `man highlight`. That will give you all the documentation for the `highlight` command which this extension uses.

**Comment by NylonDiamond** [comment]
Ah, that makes sense. Thanks again

**Comment by NylonDiamond** [comment]
Any idea where the .algenerator is located? I've checked in the quicklook folders under user, System, and library. No luck on finding it yet. I want to find it in order to see if I can override the default qlgenerator being used for my XML files. Thanks

**Comment by alexclst** [comment]
There is no qlgenerator for this plugin, that whole format and API is deprecated with Catalina (the whole reason why this app came into being in the first place, as QLColorCode broke in Catalina). Instead, this app has the Quick Look App Extension embedded in the app itself. You will see that it is an option in the _Quick Look_ section of the _Extensions_ pane in _System Preferences_. Beyond that, if you’re curious, the extension itself is in the app bundle at /Contents/Plugins (you can _Show Package Contents_ in Finder with the app selected to see these folders). But the app and extension are built together from source and macOS may refuse to run them if you edit the files in the app bundle (due to code signing, SIP, Gatekeeper, and other security systems in macOS). So, you really cannot change anything about how this plugin works without getting @sbarex to make the change to the source code, or making it yourself and opening a pull request. macOS will never use a qlgenerator for a file format that a Quick Look App Extension supports, I’ve found this out myself with JSON files, since I had an old plugin that pretty-printed JSON and had controls to collapse sections of files as well, neither of which this plugin yet does.

**Comment by NylonDiamond** [comment]
Wow, okay good to know. Thanks for the explanation. Not much I can do about it it sounds like. It's all good, we'll keep building up this app until it has all the features we want. (Then apple will break it again with the next update)

**Comment by sbarex** [comment]
Ok, I have reviewed the preferences interface adding the management of the word wrap. Please remove from manual extra arguments any `-W`, `-V`, `-J`, `--line-length`, `--wrap-no-numbers` parameter.
I also added the option to display a toolbar. For now it only supports copying the selection to the clipboard. The quicklook extension does not allow keyboard interactions within the view.

**Comment by sbarex** [comment]
> Any idea where the .algenerator is located? I've checked in the quicklook folders under user, System, and library. No luck on finding it yet. I want to find it in order to see if I can override the default qlgenerator being used for my XML files. Thanks

As @alexclst explained, the new quicklook extension use a different method instead qlgenerators.
For now, my the released precompiled app is not signed, so you can try to edit the .plist files, colorize.sh, example.*, … as you want.
