### ISSUE TITLE
.theme format

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#61]
Ironically it doesn't show ".theme" files

<img width="746" alt="Ekran Resmi 2021-01-07 04 35 50" src="https://user-images.githubusercontent.com/36481442/103840057-d517de00-50a1-11eb-92b5-11201b334fe4.png">

**Comment by sbarex** [comment]
The syntax of .theme files is `Lua`. I don't manage the preview because I doubt that many people need to view these files used only by `highlight`. The extension is also very common and there is a very high probability that there are other files with the same extension but written with other languages.
