### ISSUE TITLE
Support CMakeLists.txt.

### ISSUE THREAD

**Issue by zhouzq-thu** [sbarex/SourceCodeSyntaxHighlight#73]
Easy to use.
- Please support `CMakeLists.txt`.
- Create a switch to toggle on/off SyntaxHighlight.

**Comment by sbarex** [comment]
Hi,
is not possible to support `CMakeLists.txt` beacuse the file recognition is based on the UTI system, which in turn is based on extensions and cannot consider the full file name.

Also I'm not sure if Apple allows to manage `txt` extensions. Many common formats (images, videos, xml, ...) are always managed by the operating system. 

Finally, it is not possible to enable / disable support for single formats. Managed formats are registered in a .plist file within the extension. This file cannot be modified otherwise the application would no longer be valid.
